#include <map>
#include <string>
#include "http_handler.hpp"
static const std::pair<std::string,std::string> a[] ={ \
std::pair<std::string,std::string>(std::string(""),std::string("text/plain")), \
std::pair<std::string,std::string>(std::string("html"),std::string("text/html")), \
std::pair<std::string,std::string>(std::string("htm"),std::string("text/html")), \
std::pair<std::string,std::string>(std::string("shtml"),std::string("text/html")), \
std::pair<std::string,std::string>(std::string("css"),std::string("text/css")), \
std::pair<std::string,std::string>(std::string("xml"),std::string("text/xml")), \
std::pair<std::string,std::string>(std::string("gif"),std::string("image/gif")), \
std::pair<std::string,std::string>(std::string("jpeg"),std::string("image/jpeg")), \
std::pair<std::string,std::string>(std::string("jpg"),std::string("image/jpeg")), \
std::pair<std::string,std::string>(std::string("js"),std::string("application/javascript")), \
std::pair<std::string,std::string>(std::string("atom"),std::string("application/atom+xml")), \
std::pair<std::string,std::string>(std::string("rss"),std::string("application/rss+xml")), \
std::pair<std::string,std::string>(std::string("mml"),std::string("text/mathml")), \
std::pair<std::string,std::string>(std::string("txt"),std::string("text/plain")), \
std::pair<std::string,std::string>(std::string("jad"),std::string("text/vnd.sun.j2me.app-descriptor")), \
std::pair<std::string,std::string>(std::string("wml"),std::string("text/vnd.wap.wml")), \
std::pair<std::string,std::string>(std::string("htc"),std::string("text/x-component")), \
std::pair<std::string,std::string>(std::string("avif"),std::string("image/avif")), \
std::pair<std::string,std::string>(std::string("png"),std::string("image/png")), \
std::pair<std::string,std::string>(std::string("svg"),std::string("image/svg+xml")), \
std::pair<std::string,std::string>(std::string("svgz"),std::string("image/svg+xml")), \
std::pair<std::string,std::string>(std::string("tif"),std::string("image/tiff")), \
std::pair<std::string,std::string>(std::string("tiff"),std::string("image/tiff")), \
std::pair<std::string,std::string>(std::string("wbmp"),std::string("image/vnd.wap.wbmp")), \
std::pair<std::string,std::string>(std::string("webp"),std::string("image/webp")), \
std::pair<std::string,std::string>(std::string("ico"),std::string("image/x-icon")), \
std::pair<std::string,std::string>(std::string("jng"),std::string("image/x-jng")), \
std::pair<std::string,std::string>(std::string("bmp"),std::string("image/x-ms-bmp")), \
std::pair<std::string,std::string>(std::string("woff"),std::string("font/woff")), \
std::pair<std::string,std::string>(std::string("woff2"),std::string("font/woff2")), \
std::pair<std::string,std::string>(std::string("jar"),std::string("application/java-archive")), \
std::pair<std::string,std::string>(std::string("war"),std::string("application/java-archive")), \
std::pair<std::string,std::string>(std::string("ear"),std::string("application/java-archive")), \
std::pair<std::string,std::string>(std::string("json"),std::string("application/json")), \
std::pair<std::string,std::string>(std::string("hqx"),std::string("application/mac-binhex40")), \
std::pair<std::string,std::string>(std::string("doc"),std::string("application/msword")), \
std::pair<std::string,std::string>(std::string("pdf"),std::string("application/pdf")), \
std::pair<std::string,std::string>(std::string("ps"),std::string("application/postscript")), \
std::pair<std::string,std::string>(std::string("eps"),std::string("application/postscript")), \
std::pair<std::string,std::string>(std::string("ai"),std::string("application/postscript")), \
std::pair<std::string,std::string>(std::string("rtf"),std::string("application/rtf")), \
std::pair<std::string,std::string>(std::string("m3u8"),std::string("application/vnd.apple.mpegurl")), \
std::pair<std::string,std::string>(std::string("kml"),std::string("application/vnd.google-earth.kml+xml")), \
std::pair<std::string,std::string>(std::string("kmz"),std::string("application/vnd.google-earth.kmz")), \
std::pair<std::string,std::string>(std::string("xls"),std::string("application/vnd.ms-excel")), \
std::pair<std::string,std::string>(std::string("eot"),std::string("application/vnd.ms-fontobject")), \
std::pair<std::string,std::string>(std::string("ppt"),std::string("application/vnd.ms-powerpoint")), \
std::pair<std::string,std::string>(std::string("odg"),std::string("application/vnd.oasis.opendocument.graphics")), \
std::pair<std::string,std::string>(std::string("odp"),std::string("application/vnd.oasis.opendocument.presentation")), \
std::pair<std::string,std::string>(std::string("ods"),std::string("application/vnd.oasis.opendocument.spreadsheet")), \
std::pair<std::string,std::string>(std::string("odt"),std::string("application/vnd.oasis.opendocument.text")), \
std::pair<std::string,std::string>(std::string("pptx"),std::string("application/vnd.openxmlformats-officedocument.presentationml.presentation")), \
std::pair<std::string,std::string>(std::string("xlsx"),std::string("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")), \
std::pair<std::string,std::string>(std::string("docx"),std::string("application/vnd.openxmlformats-officedocument.wordprocessingml.document")), \
std::pair<std::string,std::string>(std::string("wmlc"),std::string("application/vnd.wap.wmlc")), \
std::pair<std::string,std::string>(std::string("wasm"),std::string("application/wasm")), \
std::pair<std::string,std::string>(std::string("7z"),std::string("application/x-7z-compressed")), \
std::pair<std::string,std::string>(std::string("cco"),std::string("application/x-cocoa")), \
std::pair<std::string,std::string>(std::string("jardiff"),std::string("application/x-java-archive-diff")), \
std::pair<std::string,std::string>(std::string("jnlp"),std::string("application/x-java-jnlp-file")), \
std::pair<std::string,std::string>(std::string("run"),std::string("application/x-makeself")), \
std::pair<std::string,std::string>(std::string("pl"),std::string("application/x-perl")), \
std::pair<std::string,std::string>(std::string("pm"),std::string("application/x-perl")), \
std::pair<std::string,std::string>(std::string("prc"),std::string("application/x-pilot")), \
std::pair<std::string,std::string>(std::string("pdb"),std::string("application/x-pilot")), \
std::pair<std::string,std::string>(std::string("rar"),std::string("application/x-rar-compressed")), \
std::pair<std::string,std::string>(std::string("rpm"),std::string("application/x-redhat-package-manager")), \
std::pair<std::string,std::string>(std::string("sea"),std::string("application/x-sea")), \
std::pair<std::string,std::string>(std::string("swf"),std::string("application/x-shockwave-flash")), \
std::pair<std::string,std::string>(std::string("sit"),std::string("application/x-stuffit")), \
std::pair<std::string,std::string>(std::string("tcl"),std::string("application/x-tcl")), \
std::pair<std::string,std::string>(std::string("tk"),std::string("application/x-tcl")), \
std::pair<std::string,std::string>(std::string("der"),std::string("application/x-x509-ca-cert")), \
std::pair<std::string,std::string>(std::string("pem"),std::string("application/x-x509-ca-cert")), \
std::pair<std::string,std::string>(std::string("crt"),std::string("application/x-x509-ca-cert")), \
std::pair<std::string,std::string>(std::string("xpi"),std::string("application/x-xpinstall")), \
std::pair<std::string,std::string>(std::string("xhtml"),std::string("application/xhtml+xml")), \
std::pair<std::string,std::string>(std::string("xspf"),std::string("application/xspf+xml")), \
std::pair<std::string,std::string>(std::string("zip"),std::string("application/zip")), \
std::pair<std::string,std::string>(std::string("bin"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("exe"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("dll"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("deb"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("dmg"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("iso"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("img"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("msi"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("msp"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("msm"),std::string("application/octet-stream")), \
std::pair<std::string,std::string>(std::string("mid"),std::string("audio/midi")), \
std::pair<std::string,std::string>(std::string("midi"),std::string("audio/midi")), \
std::pair<std::string,std::string>(std::string("kar"),std::string("audio/midi")), \
std::pair<std::string,std::string>(std::string("mp3"),std::string("audio/mpeg")), \
std::pair<std::string,std::string>(std::string("ogg"),std::string("audio/ogg")), \
std::pair<std::string,std::string>(std::string("m4a"),std::string("audio/x-m4a")), \
std::pair<std::string,std::string>(std::string("ra"),std::string("audio/x-realaudio")), \
std::pair<std::string,std::string>(std::string("3gpp"),std::string("video/3gpp")), \
std::pair<std::string,std::string>(std::string("3gp"),std::string("video/3gpp")), \
std::pair<std::string,std::string>(std::string("ts"),std::string("video/mp2t")), \
std::pair<std::string,std::string>(std::string("mp4"),std::string("video/mp4")), \
std::pair<std::string,std::string>(std::string("mpeg"),std::string("video/mpeg")), \
std::pair<std::string,std::string>(std::string("mpg"),std::string("video/mpeg")), \
std::pair<std::string,std::string>(std::string("mov"),std::string("video/quicktime")), \
std::pair<std::string,std::string>(std::string("webm"),std::string("video/webm")), \
std::pair<std::string,std::string>(std::string("flv"),std::string("video/x-flv")), \
std::pair<std::string,std::string>(std::string("m4v"),std::string("video/x-m4v")), \
std::pair<std::string,std::string>(std::string("mng"),std::string("video/x-mng")), \
std::pair<std::string,std::string>(std::string("asx"),std::string("video/x-ms-asf")), \
std::pair<std::string,std::string>(std::string("asf"),std::string("video/x-ms-asf")), \
std::pair<std::string,std::string>(std::string("wmv"),std::string("video/x-ms-wmv")), \
std::pair<std::string,std::string>(std::string("avi"),std::string("video/x-msvideo")), \
};
const std::map<std::string, std::string> http_handler::mime(std::begin(a),std::end(a));
